// AUTO-GENERATED by verif/spike/gen_golden.py from riscvtest_pipe_csr.txt.
// Reference model: Spike RISC-V ISA Simulator 1.1.1-dev
// Do not hand-edit -- regenerate with verif/spike/regen.sh.
    expect_reg[0] = 32'h00000000;
    expect_reg[1] = 32'h00000088;
    expect_reg[2] = 32'h00000111;
    expect_reg[3] = 32'h00000222;
    expect_reg[4] = 32'h00000001;
    expect_reg[5] = 32'h00000000;
    expect_reg[6] = 32'h00000333;
    expect_reg[7] = 32'h00000002;
    expect_reg[8] = 32'h00000444;
    expect_reg[9] = 32'h00000055;
    expect_reg[10] = 32'h00000000;
    expect_reg[11] = 32'h00000055;
    expect_reg[12] = 32'h00000030;
    expect_reg[13] = 32'h00000055;
    expect_reg[14] = 32'h00000075;
    expect_reg[15] = 32'h00000045;
    expect_reg[16] = 32'h00030000;
    expect_reg[17] = 32'h00000041;
    expect_reg[18] = 32'h00000042;
    expect_reg[19] = 32'h00000080;
    expect_reg[20] = 32'h80000007;
    expect_reg[21] = 32'h00000000;
    expect_reg[22] = 32'h00000001;
    expect_reg[23] = 32'hffffffff;
    expect_reg[24] = 32'h00020000;
    expect_reg[25] = 32'h00000555;
    expect_reg[26] = 32'h00000042;
    expect_reg[27] = 32'h00000007;
    expect_reg[28] = 32'h00000001;
    expect_reg[29] = 32'h00000001;
    expect_reg[30] = 32'h00000002;
    expect_reg[31] = 32'h00000001;
