// AUTO-GENERATED by verif/spike/gen_golden.py from riscvtest_pipe.txt.
// Reference model: Spike RISC-V ISA Simulator 1.1.1-dev
// Do not hand-edit -- regenerate with verif/spike/regen.sh.
    expect_reg[0] = 32'h00000000;
    expect_reg[1] = 32'h0000000a;
    expect_reg[2] = 32'h00000014;
    expect_reg[3] = 32'h0000001e;
    expect_reg[4] = 32'h00000005;
    expect_reg[5] = 32'h0000000a;
    expect_reg[6] = 32'h00000000;
    expect_reg[7] = 32'h00000055;
    expect_reg[8] = 32'h00000055;
    expect_reg[9] = 32'h00000056;
    expect_reg[10] = 32'h00000004;
    expect_reg[11] = 32'h00000077;
    expect_reg[12] = 32'h00000077;
    expect_reg[13] = 32'h00000001;
    expect_reg[14] = 32'h00000001;
    expect_reg[15] = 32'h00000001;
    expect_reg[16] = 32'h00000002;
    expect_reg[17] = 32'h00000058;
    expect_reg[18] = 32'h00000000;
    expect_reg[19] = 32'h00000001;
    expect_reg[20] = 32'h00000002;
    expect_reg[21] = 32'h00000001;
    expect_reg[22] = 32'h00000001;
    expect_reg[23] = 32'h00000000;
    expect_reg[24] = 32'h00000000;
    expect_reg[25] = 32'h00000000;
    expect_reg[26] = 32'h00000000;
    expect_reg[27] = 32'h00000000;
    expect_reg[28] = 32'h00000000;
    expect_reg[29] = 32'h00000000;
    expect_reg[30] = 32'h00000000;
    expect_reg[31] = 32'h00000000;
    expect_mem_w0 = 32'h00000055;
    expect_mem_w1 = 32'h00000077;
