// =============================================================================
// verif/uvm/rv32i_uvm_pkg.sv
//
// The UVM environment itself: transactions, a randomized/hazard-biased
// instruction-stream sequence, a backdoor-loading driver, a retirement
// monitor, and a scoreboard that lockstep-checks every real retirement
// against the ISS golden model (iss/, via the DPI-C bridge in
// iss_dpi.cc). This is the architecture DESIGN_GUIDE.md's Section 7
// scoped out before any of this was built: a commit/retire interface
// sampled by a monitor, checked against a DPI golden model -- the same
// shape used by the two real UVM-for-RISC-V references that section
// cites (gopro-uvm-rtl-verification, OpenHW core-v-verif).
//
// Scope, stated explicitly rather than left implicit: v1 generates
// R-type ALU, I-type ALU (excluding shift-immediate), LOAD, STORE, and
// forward-only BRANCH instructions. JAL/JALR/LUI/AUIPC/SYSTEM (ECALL,
// CSR ops, MRET) are deliberately out of scope for this pass -- adding
// them is a natural, bounded v2 extension, not a gap that was missed.
// Excluding SYSTEM in particular means this environment does not yet
// exercise the trap/interrupt/CSR machinery; tb_pipe_csr (rtl/tb_pipe.sv)
// remains the directed test covering that path until a v2 sequence adds
// it here too.
// =============================================================================

package rv32i_uvm_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import rv32i_pkg::*;

  // No DPI-C. The golden model is Spike, run ahead of time by
  // verif/spike/gen_stream.py, which emits stream.hex (the program) and
  // stream_trace.txt (the expected retirements). See the scoreboard's header
  // for why the reference is precomputed rather than called live.

  // ===========================================================================
  // rv32i_instr_txn: one instruction word to be written into imem.
  //
  //   instr   - the 32-bit instruction word.
  //   last_word - set on the final word of a program. Signals the driver to
  //               stop pulling items and release reset.
  // ===========================================================================
  class rv32i_instr_txn extends uvm_sequence_item;
    rand bit [31:0] instr;
    bit             last_word;

    `uvm_object_utils_begin(rv32i_instr_txn)
      `uvm_field_int(instr, UVM_ALL_ON)
      `uvm_field_int(last_word, UVM_ALL_ON)
    `uvm_object_utils_end

    function new(string name = "rv32i_instr_txn");
      super.new(name);
    endfunction
  endclass

  // ===========================================================================
  // rv32i_retire_txn: one retired instruction, as observed at writeback.
  // Emitted exactly once per instruction, gated on retire_if.sv's retire_valid 
  //
  //   pc       - PC of the retiring instruction
  //   instr    - the retiring instruction 
  //   rd       - destination register, if any
  //   wdata    - value written to rd
  //   regwrite - set if this instruction wrote a register
  // ===========================================================================
  class rv32i_retire_txn extends uvm_sequence_item;
    bit [31:0] pc;
    bit [31:0] instr;
    bit [4:0]  rd;
    bit [31:0] wdata;
    bit        regwrite;

    `uvm_object_utils_begin(rv32i_retire_txn)
      `uvm_field_int(pc, UVM_ALL_ON)
      `uvm_field_int(instr, UVM_ALL_ON)
      `uvm_field_int(rd, UVM_ALL_ON)
      `uvm_field_int(wdata, UVM_ALL_ON)
      `uvm_field_int(regwrite, UVM_ALL_ON)
    `uvm_object_utils_end

    function new(string name = "rv32i_retire_txn");
      super.new(name);
    endfunction
  endclass

  typedef uvm_sequencer #(rv32i_instr_txn) rv32i_sequencer;

  // ===========================================================================
  // Sequence: replays the instruction stream generated by
  // verif/spike/gen_stream.py, read from stream.hex.
  //
  // Generation used to happen here, in body(), with procedural
  // $urandom_range() calls. It moved out to Python for one reason: the
  // reference model moved out too. The scoreboard now checks against a Spike
  // trace precomputed for this exact program (see its header for why Spike
  // cannot be called live), and a precomputed trace only means anything if the
  // program it was computed from is the program the DUT runs. Generating the
  // stream in one place and the reference in another, from different random
  // number generators, would be a scoreboard that checks nothing.
  //
  // The generation *policy* is unchanged and now lives in gen_stream.py --
  // same hazard bias (~40% of instructions take rs1 from the previous
  // instruction's rd, per DESIGN_GUIDE.md Section 7 Step 3), same
  // safety-by-construction rules:
  //  - x1 is reserved as a "safe base pointer" for all loads/stores, seeded to
  //    0 by the first instruction and never used as another destination, so
  //    every offset is known at generation time to be small, aligned, and far
  //    from the MMIO window at 0x00020000. Same "reserve a pointer register"
  //    technique riscv-dv uses.
  //  - branches only ever jump forward by a small bounded amount.
  //  - the last instruction is a fixed sentinel (rd=x31, a recognizable
  //    immediate) the scoreboard watches for as the "program fully retired"
  //    signal, rather than inferring completion from pipeline timing.
  //
  // gen_stream.py also fixes a latent bug in the old in-simulator version: a
  // forward branch among the last few instructions could jump *past* the end
  // of the program into unwritten memory. Padding NOPs are now emitted before
  // the sentinel so every branch target lands inside the program.
  //
  // Stimulus is therefore fixed per seed rather than per simulation run. New
  // stimulus means re-running gen_stream.py with a new --seed. For a
  // regression that is arguably an improvement, since a failing seed is
  // reproducible by name.
  // ===========================================================================
  class rv32i_random_seq extends uvm_sequence #(rv32i_instr_txn);
    `uvm_object_utils(rv32i_random_seq)

    // The instruction encoders and the $urandom_range generation loop that
    // used to live here moved to verif/spike/gen_stream.py -- see this class's
    // header. Program length is now a gen_stream.py argument (--num-instr),
    // not a runtime plusarg, because the reference trace is computed from the
    // same program and the two have to agree.

    function new(string name = "rv32i_random_seq");
      super.new(name);
    endfunction

    task send(bit [31:0] w, bit last = 1'b0);
      rv32i_instr_txn req;
      req = rv32i_instr_txn::type_id::create("req");
      start_item(req);
      req.instr   = w;
      req.last_word = last;
      finish_item(req);
    endtask

    task body();
      int        fd, code;
      int        word;
      bit [31:0] words[$];
      string     hex_file;

      if (!$value$plusargs("STREAM=%s", hex_file))
        hex_file = "stream.hex";

      fd = $fopen(hex_file, "r");
      if (fd == 0)
        `uvm_fatal("NOSTREAM",
          $sformatf("cannot open instruction stream '%s' -- generate it with verif/spike/gen_stream.py",
                    hex_file))

      while (!$feof(fd)) begin
        code = $fscanf(fd, "%h\n", word);
        if (code == 1) words.push_back(word);
      end
      $fclose(fd);

      if (words.size() == 0)
        `uvm_fatal("NOSTREAM", $sformatf("instruction stream '%s' was empty", hex_file))

      `uvm_info("SEQ", $sformatf("loaded %0d instruction words from %s",
                                 words.size(), hex_file), UVM_LOW)

      foreach (words[i])
        send(words[i], (i == words.size() - 1));
    endtask
  endclass

  // ===========================================================================
  // Driver: holds reset, backdoor-loads the sequence's instruction stream
  // into imem's RAM via mem_backdoor_if (see mem_backdoor_if.sv/
  // mem_backdoor_bind.sv), then releases reset and lets the DUT run.
  // ===========================================================================
  class rv32i_driver extends uvm_driver #(rv32i_instr_txn);
    `uvm_component_utils(rv32i_driver)

    virtual rv32i_if        vif;
    virtual mem_backdoor_if bd_vif;

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      if (!uvm_config_db#(virtual rv32i_if)::get(this, "", "vif", vif))
        `uvm_fatal("NOVIF", "rv32i_driver: no rv32i_if found in config_db")
      if (!uvm_config_db#(virtual mem_backdoor_if)::get(this, "", "bd_vif", bd_vif))
        `uvm_fatal("NOVIF", "rv32i_driver: no mem_backdoor_if found in config_db")
    endfunction

    task run_phase(uvm_phase phase);
      rv32i_instr_txn req;
      int             idx;
      bit             done;

      // hold the DUT in reset while the program is backdoor-loaded
      vif.reset = 1'b1;
      repeat (2) @(posedge vif.clk);

      idx  = 0;
      done = 1'b0;
      while (!done) begin
        seq_item_port.get_next_item(req);
        bd_vif.load_word(idx, req.instr);
        idx++;
        done = req.last_word;
        seq_item_port.item_done();
      end
      `uvm_info("DRIVER", $sformatf("backdoor-loaded %0d instruction words", idx), UVM_LOW)

      // release reset -- the loaded program starts fetching from word 0
      repeat (2) @(posedge vif.clk);
      vif.reset = 1'b0;
    endtask
  endclass

  // ===========================================================================
  // Monitor: samples retire_if.sv's MON modport every cycle, publishes one
  // rv32i_retire_txn per cycle where retire_valid is set -- the
  // definitive "a real instruction retired" signal (see retire_if.sv).
  // ===========================================================================
  class rv32i_monitor extends uvm_monitor;
    `uvm_component_utils(rv32i_monitor)

    virtual retire_if.MON            vif;
    uvm_analysis_port #(rv32i_retire_txn) ap;

    function new(string name, uvm_component parent);
      super.new(name, parent);
      ap = new("ap", this);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      if (!uvm_config_db#(virtual retire_if.MON)::get(this, "", "retire_vif", vif))
        `uvm_fatal("NOVIF", "rv32i_monitor: no retire_if.MON found in config_db")
    endfunction

    task run_phase(uvm_phase phase);
      rv32i_retire_txn txn;
      forever begin
        @(vif.mon_cb);
        if (vif.mon_cb.retire_valid) begin
          txn = rv32i_retire_txn::type_id::create("txn");
          txn.pc       = vif.mon_cb.pc;
          txn.instr    = vif.mon_cb.instr;
          txn.rd       = vif.mon_cb.rd;
          txn.wdata    = vif.mon_cb.wdata;
          txn.regwrite = vif.mon_cb.regwrite_valid;
          ap.write(txn);
        end
      end
    endtask
  endclass

  // ===========================================================================
  // Scoreboard: lockstep-checks every real retirement against a reference
  // trace produced by Spike (verif/spike/gen_stream.py), read from
  // stream_trace.txt at build time.
  //
  // This used to call a hand-written C++ ISS live over DPI-C. That ISS was
  // deleted -- a golden model written by the same author as the RTL, from the
  // same reading of the spec, cannot catch a misreading of the spec. Spike
  // replaces it, but NOT in the same place: this environment's only documented
  // way to run is EDA Playground, which compiles DPI C files by uploading them
  // next to the SystemVerilog. The old ISS was four self-contained files, so
  // that worked; Spike is a library with boost/libfdt dependencies and cannot
  // be uploaded. A live Spike-over-DPI bridge would leave this environment
  // with no way to run at all.
  //
  // Reading a precomputed trace keeps Spike as the authority while removing
  // the DPI-C dependency entirely -- no C compiler, no plugins, just $fscanf.
  // The cost is that stimulus is fixed at generation time: new stimulus means
  // re-running gen_stream.py with a new --seed rather than re-running the
  // simulation. For a regression that is arguably better, since a failing seed
  // is reproducible by name, but it is a real change in how this is driven.
  //
  // Two checks per retirement, both real bug classes for a pipeline:
  //  - control-flow: the retiring PC must equal the reference's PC for this
  //    retirement index (catches wrong branch targets/conditions).
  //  - register value: if this instruction wrote a register, the value must
  //    match, skipped for rd==x0 (an architectural no-op on both sides --
  //    the same convention used throughout this project's directed tests).
  // ===========================================================================
  `uvm_analysis_imp_decl(_retire)

  class rv32i_scoreboard extends uvm_component;
    `uvm_component_utils(rv32i_scoreboard)

    localparam bit [31:0] SENTINEL_VAL = 32'h000007FF;
    localparam bit [4:0]  SENTINEL_REG = 5'd31;

    // Reference trace, loaded from stream_trace.txt in build_phase.
    localparam int unsigned MAX_TRACE = 100000;
    bit [31:0] ref_pc    [MAX_TRACE];
    bit [31:0] ref_instr [MAX_TRACE];
    bit [4:0]  ref_rd    [MAX_TRACE];
    bit [31:0] ref_wdata [MAX_TRACE];
    bit        ref_rw    [MAX_TRACE];
    int unsigned ref_len;

    uvm_analysis_imp_retire #(rv32i_retire_txn, rv32i_scoreboard) retire_export;

    int unsigned num_checked;
    int unsigned num_mismatches;
    event        done;

    function new(string name, uvm_component parent);
      super.new(name, parent);
      retire_export = new("retire_export", this);
    endfunction

    function void build_phase(uvm_phase phase);
      int fd, code;
      int pc, instr, rd, wdata, rw;
      string trace_file;
      super.build_phase(phase);

      num_checked    = 0;
      num_mismatches = 0;
      ref_len        = 0;

      if (!$value$plusargs("TRACE=%s", trace_file))
        trace_file = "stream_trace.txt";

      fd = $fopen(trace_file, "r");
      if (fd == 0)
        `uvm_fatal("NOTRACE",
          $sformatf("cannot open reference trace '%s' -- generate it with verif/spike/gen_stream.py",
                    trace_file))

      // Columns: pc instr rd wdata regwrite, all hex except rd/regwrite.
      // Comment lines start with '/' and are skipped by the failed match.
      while (!$feof(fd) && ref_len < MAX_TRACE) begin
        code = $fscanf(fd, "%h %h %d %h %d\n", pc, instr, rd, wdata, rw);
        if (code == 5) begin
          ref_pc[ref_len]    = pc;
          ref_instr[ref_len] = instr;
          ref_rd[ref_len]    = rd[4:0];
          ref_wdata[ref_len] = wdata;
          ref_rw[ref_len]    = rw[0];
          ref_len++;
        end else begin
          void'($fgets(trace_file, fd));   // not a data row -- discard the line
        end
      end
      $fclose(fd);

      if (ref_len == 0)
        `uvm_fatal("NOTRACE", $sformatf("reference trace '%s' contained no rows", trace_file))

      `uvm_info("SCOREBOARD",
        $sformatf("loaded %0d reference retirements from %s", ref_len, trace_file), UVM_LOW)
    endfunction

    function void write_retire(rv32i_retire_txn t);
      if (num_checked >= ref_len) begin
        `uvm_error("TRACE_OVERRUN",
          $sformatf("retirement #%0d but the reference trace has only %0d entries (instr=0x%08h)",
                    num_checked, ref_len, t.instr))
        num_mismatches++;
        return;
      end

      // ---- control-flow check ----
      if (ref_pc[num_checked] !== t.pc) begin
        `uvm_error("PC_MISMATCH",
          $sformatf("retirement #%0d: RTL pc=0x%08h, Spike expected pc=0x%08h (instr=0x%08h)",
                    num_checked, t.pc, ref_pc[num_checked], t.instr))
        num_mismatches++;
      end

      // ---- the instruction itself must be the one Spike executed ----
      if (ref_instr[num_checked] !== t.instr) begin
        `uvm_error("INSTR_MISMATCH",
          $sformatf("retirement #%0d: RTL retired instr=0x%08h, Spike executed 0x%08h (pc=0x%08h)",
                    num_checked, t.instr, ref_instr[num_checked], t.pc))
        num_mismatches++;
      end

      // ---- register-value check, skipped for x0 ----
      if (t.regwrite && (t.rd != 5'd0)) begin
        if (!ref_rw[num_checked] || ref_rd[num_checked] !== t.rd ||
            ref_wdata[num_checked] !== t.wdata) begin
          `uvm_error("REG_MISMATCH",
            $sformatf("retirement #%0d: RTL wrote x%0d=0x%08h, Spike wrote x%0d=0x%08h (rw=%0d, instr=0x%08h, pc=0x%08h)",
                      num_checked, t.rd, t.wdata,
                      ref_rd[num_checked], ref_wdata[num_checked], ref_rw[num_checked],
                      t.instr, t.pc))
          num_mismatches++;
        end
      end

      num_checked++;

      if (t.regwrite && (t.rd == SENTINEL_REG) && (t.wdata == SENTINEL_VAL)) begin
        `uvm_info("SCOREBOARD",
          $sformatf("sentinel retired -- %0d instructions checked, %0d mismatches",
                    num_checked, num_mismatches), UVM_LOW)
        -> done;
      end
    endfunction
  endclass

  // ===========================================================================
  // Agent, env, test -- standard UVM wiring, nothing project-specific here.
  // ===========================================================================
  class rv32i_agent extends uvm_agent;
    `uvm_component_utils(rv32i_agent)

    rv32i_sequencer sqr;
    rv32i_driver    drv;
    rv32i_monitor   mon;

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      sqr = rv32i_sequencer::type_id::create("sqr", this);
      drv = rv32i_driver::type_id::create("drv", this);
      mon = rv32i_monitor::type_id::create("mon", this);
    endfunction

    function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      drv.seq_item_port.connect(sqr.seq_item_export);
    endfunction
  endclass

  class rv32i_env extends uvm_env;
    `uvm_component_utils(rv32i_env)

    rv32i_agent      agt;
    rv32i_scoreboard sb;

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      agt = rv32i_agent::type_id::create("agt", this);
      sb  = rv32i_scoreboard::type_id::create("sb", this);
    endfunction

    function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      agt.mon.ap.connect(sb.retire_export);
    endfunction
  endclass

  class rv32i_random_test extends uvm_test;
    `uvm_component_utils(rv32i_random_test)

    rv32i_env env;

    function new(string name, uvm_component parent);
      super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
      super.build_phase(phase);
      env = rv32i_env::type_id::create("env", this);
    endfunction

    task run_phase(uvm_phase phase);
      rv32i_random_seq seq;

      phase.raise_objection(this);

      // Program length is no longer a runtime plusarg: the program and its
      // Spike reference trace are generated together by
      // verif/spike/gen_stream.py --num-instr, and changing one without the
      // other would give a scoreboard checking against the wrong program.
      // +STREAM=<file> / +TRACE=<file> select which generated pair to use.
      seq = rv32i_random_seq::type_id::create("seq");
      seq.start(env.agt.sqr);

      // wait for the scoreboard to see the sentinel retire, plus a small
      // margin for the pipeline to drain
      @(env.sb.done);
      repeat (10) @(posedge env.agt.drv.vif.clk);

      `uvm_info("TEST",
        $sformatf("DONE -- %0d instructions checked, %0d mismatches",
                  env.sb.num_checked, env.sb.num_mismatches), UVM_LOW)
      if (env.sb.num_mismatches == 0)
        `uvm_info("TEST", "*** UVM TEST PASSED ***", UVM_NONE)
      else
        `uvm_error("TEST",
          $sformatf("*** UVM TEST FAILED -- %0d mismatches ***", env.sb.num_mismatches))

      phase.drop_objection(this);
    endtask
  endclass

endpackage
